name: Backend CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Backend test
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Start MongoDB
        run: |
          sudo service mongod start

      - name: Start server.js
        run: npm start &

      - name: Run tests
        run: npm test

      - name: Stop MongoDB
        run: |
          sudo service mongod stop
